import * as React from "react";
import { CheckCircle2, Download, ExternalLink, Printer, ShoppingCart } from "lucide-react";
import QRCode from "qrcode";
import { useCalendarConfig, useCompleteSale, usePrintAttempt, useSession, saleArtifactUrl, type TicketLineInput, type PaymentMethod, useClient } from "@kiddy-land/client/react";
import { formatIdr } from "@kiddy-land/localization";
import { useLocale } from "@workspace/ui/lib/i18n";
import { Button } from "@workspace/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { Alert, AlertDescription, AlertTitle } from "@workspace/ui/components/alert";

export function CashierSale() {
  const { t, locale } = useLocale(); const { session } = useSession(); const client = useClient(); const config = useCalendarConfig(); const complete = useCompleteSale(); const print = usePrintAttempt();
  const [childName, setChildName] = React.useState(""); const [packageId, setPackageId] = React.useState(""); const [lines, setLines] = React.useState<TicketLineInput[]>([]); const [paymentMethod, setPaymentMethod] = React.useState<PaymentMethod>("cash"); const [confirmed, setConfirmed] = React.useState(false); const [sale, setSale] = React.useState<Awaited<ReturnType<typeof complete.mutateAsync>> | undefined>(); const [qr, setQr] = React.useState<{ name: string; dataUrl: string } | undefined>(); const [error, setError] = React.useState("");
  const packages = config.data?.packages ?? []; const selected = packages.find((item) => item.id === packageId); const operatingDate = config.data ? new Intl.DateTimeFormat("en-CA", { timeZone: config.data.timezone }).format(new Date()) : ""; const isWeekend = operatingDate ? [0, 6].includes(new Date(`${operatingDate}T12:00:00`).getDay()) : false; const total = lines.reduce((sum, line) => { const item = packages.find((pkg) => pkg.id === line.packageId); return sum + (item ? (isWeekend ? item.weekendPrice : item.weekdayPrice) : 0); }, 0);
  const addLine = () => { if (!childName.trim() || !selected) return; setLines([...lines, { childId: `child_${crypto.randomUUID()}`, childName: childName.trim(), packageId: selected.id, paymentConfirmed: paymentMethod === "cash" }]); setChildName(""); };
  const finalize = async () => { if (!session?.user || !lines.length || !config.data) return; setError(""); try { setSale(await complete.mutateAsync({ idempotencyKey: crypto.randomUUID(), cashierId: session.user.id, operatingDate: new Intl.DateTimeFormat("en-CA", { timeZone: config.data.timezone }).format(new Date()), lines: lines.map((line) => ({ ...line, paymentConfirmed: paymentMethod === "cash" || confirmed })), paymentMethod, locale })); } catch (cause) { setError(cause instanceof Error ? cause.message : t("sale.error")); } };
  const artifact = async (kind: "tickets" | "receipt", action: "open" | "download" | "print" = "open") => { if (!sale) return; try { const response = await fetch(saleArtifactUrl(client.origin, sale.id, kind), { headers: { Authorization: `Bearer ${client.getToken()}` } }); if (!response.ok) throw new Error("Artifact unavailable"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${sale.receipt.number}-${kind}.pdf`; if (action === "download") anchor.click(); else { const popup = window.open(url, "_blank", "noopener"); if (!popup) throw new Error("Print window was blocked"); if (action === "print") { popup.addEventListener("load", () => popup.print(), { once: true }); } } await print.mutateAsync({ saleId: sale.id, artifact: kind, actorId: session?.user?.id ?? "cashier", status: action === "print" ? "requested" : "requested", reprint: false }); } catch (cause) { try { await print.mutateAsync({ saleId: sale.id, artifact: kind, actorId: session?.user?.id ?? "cashier", status: "unknown", reprint: false, reason: cause instanceof Error ? cause.message : "Artifact action failed" }); } catch { /* preserve the original artifact error */ } setError(cause instanceof Error ? cause.message : t("sale.error")); } };
  if (sale) return <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="text-primary" />{t("sale.completed")}</CardTitle><CardDescription>{sale.receipt.number} · {formatIdr(sale.total, locale)}</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3">{sale.tickets.map((ticket) => <div className="flex items-center justify-between border p-3" key={ticket.id}><div><p className="font-medium">{ticket.childName ?? ticket.childId}</p><p className="font-mono text-xs text-muted-foreground">{ticket.code}</p></div><span aria-hidden="true">QR</span></div>)}</div><div className="flex flex-wrap gap-2"><Button onClick={() => void artifact("tickets", "print")}><Printer data-icon="inline-start" />{t("sale.printTickets")}</Button><Button variant="outline" onClick={() => void artifact("tickets", "download")}><Download data-icon="inline-start" />{t("sale.downloadTickets")}</Button><Button variant="outline" onClick={() => void artifact("receipt", "open")}><ExternalLink data-icon="inline-start" />{t("sale.openReceipt")}</Button><Button variant="outline" onClick={() => void artifact("receipt", "print")}><Printer data-icon="inline-start" />{t("sale.printReceipt")}</Button><Button variant="outline" onClick={() => { const ticket = sale.tickets[0]; if (ticket) void QRCode.toDataURL(ticket.qrToken).then((dataUrl) => setQr({ name: ticket.childName ?? ticket.childId, dataUrl })); }}>{t("sale.showQr")}</Button><Button variant="ghost" onClick={() => { setSale(undefined); setLines([]); }}>{t("sale.newSale")}</Button></div>{qr && <div role="dialog" className="grid justify-items-center gap-2 border p-4"><p className="font-medium">{qr.name}</p><img src={qr.dataUrl} alt={`${t("sale.showQr")} ${qr.name}`} className="size-48" /><Button variant="ghost" onClick={() => setQr(undefined)}>{t("sale.close")}</Button></div>}{error && <Alert variant="destructive"><AlertTitle>{t("sale.error")}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}</CardContent></Card>;
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingCart />{t("sale.title")}</CardTitle><CardDescription>{t("sale.subtitle")}</CardDescription></CardHeader><CardContent className="grid gap-5"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input className="h-10 border border-input bg-background px-3" placeholder={t("sale.childName")} value={childName} onChange={(e) => setChildName(e.target.value)} /><select className="h-10 border border-input bg-background px-3" value={packageId} onChange={(e) => setPackageId(e.target.value)}><option value="">{t("sale.choosePackage")}</option>{packages.map((item) => <option value={item.id} key={item.id}>{item.name} · {formatIdr(item.weekdayPrice, locale)}</option>)}</select><Button onClick={addLine} disabled={!childName.trim() || !selected}>{t("sale.addLine")}</Button></div><div className="grid gap-2">{lines.map((line, index) => <div className="flex justify-between border p-3 text-sm" key={`${line.childId}-${index}`}><span>{line.childName}</span><span>{packages.find((item) => item.id === line.packageId)?.name}</span></div>)}</div><div className="grid gap-3 border-t pt-4 sm:grid-cols-[1fr_auto]"><div><p className="text-sm text-muted-foreground">{t("sale.total")}</p><p className="text-2xl font-semibold">{formatIdr(total, locale)}</p></div><select className="h-10 border border-input bg-background px-3" value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value as PaymentMethod)}><option value="cash">{t("sale.cash")}</option><option value="QRIS">QRIS</option><option value="bank-transfer">{t("sale.bankTransfer")}</option></select></div>{paymentMethod !== "cash" && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />{t("sale.confirmPayment")}</label>}<Button onClick={() => void finalize()} disabled={complete.isPending || !lines.length || (paymentMethod !== "cash" && !confirmed)}>{t("sale.complete")}</Button>{error && <Alert variant="destructive"><AlertTitle>{t("sale.error")}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}</CardContent></Card>;
}
