import type { ReactNode } from "react";
import { AlertTriangle, CheckCircle2, CircleDot, LoaderCircle, RefreshCw, Server, ShieldCheck, WifiOff } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@workspace/ui/components/alert";
import { Button } from "@workspace/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { useLocale, type MessageKey } from "@workspace/ui/lib/i18n";
import { useSession } from "@kiddy-land/client/react";
import { CalendarSettings } from "@workspace/ui/components/calendar-settings";
import { useHostStatus, type HostState, type HostStatusSource } from "@workspace/ui/lib/host";
import { cn } from "@workspace/ui/lib/utils";
import { CashierSale } from "@workspace/ui/components/cashier-sale";
import { TicketScanner } from "@workspace/ui/components/ticket-scanner";

export function HostDashboard({ source, origin, onStop }: { source: HostStatusSource; origin?: string; onStop?: () => Promise<void> }) {
  const { locale, setLocale, t } = useLocale();
  const { session } = useSession();
  const { status, checking, check } = useHostStatus(source);
  const ready = status.state === "ready";
  const titleKey: MessageKey = status.state === "ready" ? "host.ready" : status.state === "fatal" ? "host.fatal" : status.state === "starting" ? "host.starting" : "host.unhealthy";
  return <main className="flex min-h-dvh flex-col gap-8 bg-background px-5 py-8 text-foreground sm:px-10"><div className="mx-auto flex w-full max-w-5xl flex-col gap-8"><header className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.25em] text-primary">{t("host.eyebrow")}</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{t("host.title")}</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">{t("host.subtitle")}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setLocale(locale === "id" ? "en" : "id")}>{locale === "id" ? "EN" : "ID"}</Button><Button variant="outline" onClick={() => void check()} disabled={checking}><RefreshCw data-icon="inline-start" className={cn(checking && "animate-spin")} />{t("host.check")}</Button></div></header><Card><CardHeader><div className="flex items-center gap-3"><Server className="text-primary" /><div><CardTitle>{t("host.readiness")}</CardTitle><CardDescription>{t("host.readinessDescription")}</CardDescription></div></div></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-6"><div className="flex items-start gap-4"><StatusIcon state={status.state} /><div><p className="text-xl font-medium">{t(titleKey)}</p><p className="mt-1 text-sm text-muted-foreground">{ready ? t("host.readyDescription") : t("host.notReadyDescription")}</p></div></div><span className="inline-flex items-center gap-2 rounded-none border border-border bg-muted px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground"><CircleDot className="size-3" />{status.state}</span></CardContent></Card><section className="grid gap-4 sm:grid-cols-3"><InfoCard icon={<ShieldCheck />} title={t("host.localFirst")} text={t("host.localFirstDescription")} /><InfoCard icon={<WifiOff />} title={t("host.offline")} text={t("host.offlineDescription")} /><InfoCard icon={<CheckCircle2 />} title={t("host.authoritative")} text={t("host.authoritativeDescription")} /></section>{session?.device.mode === "Cashier" && <CashierSale />}{session?.device.mode === "Entrance Scanner" && <TicketScanner kind="entry" />}{session?.device.mode === "Exit Scanner" && <TicketScanner kind="exit" />}{session?.user?.role === "Owner" && <CalendarSettings />}{onStop && <Alert variant="default"><AlertTriangle /><AlertTitle>{t("host.stop")}</AlertTitle><AlertDescription><Button variant="destructive" size="sm" onClick={() => void onStop()} disabled={checking}>{t("host.stop")}</Button></AlertDescription></Alert>}<footer className="text-xs text-muted-foreground">{status.origin ?? origin ?? t("host.stopUnavailable")}{status.database ? ` · ${t("host.database")}: ${status.database}` : ""}</footer></div></main>;
}
function StatusIcon({ state }: { state: HostState }) { if (state === "ready") return <CheckCircle2 className="mt-1 size-8 shrink-0 text-primary" />; if (state === "fatal") return <AlertTriangle className="mt-1 size-8 shrink-0 text-destructive" />; if (state === "unhealthy") return <WifiOff className="mt-1 size-8 shrink-0 text-muted-foreground" />; return <LoaderCircle className="mt-1 size-8 shrink-0 animate-spin text-primary" />; }
function InfoCard({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <Card><CardContent className="flex gap-3 pt-6"><span className="text-primary">{icon}</span><div><h2 className="font-medium">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div></CardContent></Card>; }
