import * as React from "react";
import { useMemberByCode, useRegisterMember, useSearchMembers } from "@kiddy-land/client/react";
import { Button } from "@workspace/ui/components/button";

export function MemberPicker({ onSelect }: { onSelect: (member: { id: string; childId: string; code: string; name: string; status: "active" | "deactivated" }) => void }) {
  const [code, setCode] = React.useState(""); const [name, setName] = React.useState(""); const [phone, setPhone] = React.useState(""); const [searching, setSearching] = React.useState(false); const [registeredCode, setRegisteredCode] = React.useState(""); const found = useMemberByCode(searching ? undefined : code); const matches = useSearchMembers(searching ? name : "", searching ? phone : ""); const register = useRegisterMember();
  const select = (value: { member: { id: string; childId: string; code: string; status: "active" | "deactivated" }; child: { id: string; name: string } }) => { setRegisteredCode(value.member.code); onSelect({ id: value.member.id, childId: value.child.id, code: value.member.code, name: value.child.name, status: value.member.status }); };
  return <div className="grid gap-2 border p-3"><div className="flex gap-2"><input className="h-9 border px-2" placeholder="Membership code" value={code} onChange={(e) => { setCode(e.target.value); setSearching(false); }} /><Button size="sm" onClick={() => { const value = found.data; if (value) select(value); }}>Find</Button></div><div className="flex gap-2"><input className="h-9 border px-2" placeholder="Child name" value={name} onChange={(e) => setName(e.target.value)} /><input className="h-9 border px-2" placeholder="Phone" value={phone} onChange={(e) => setPhone(e.target.value)} /><Button size="sm" variant="outline" onClick={() => { setSearching(true); void matches.refetch(); }}>{"Find by name/phone"}</Button><Button size="sm" variant="outline" onClick={() => register.mutate({ name, phone }, { onSuccess: (value) => select(value) })}>Register</Button></div>{registeredCode ? <p className="text-sm font-mono">Membership code: {registeredCode}</p> : null}{found.data ? <p className="text-sm">{found.data.child.name} · {found.data.member.status}</p> : null}{matches.data?.map((value) => <Button key={value.member.id} size="sm" variant="ghost" onClick={() => select(value)}>{value.child.name} · {value.member.status}</Button>)}</div>;
}
