import * as React from "react";
import { useMembers, useReissueMemberCode, useDeactivateMember, useReactivateMember, useMemberHistory } from "@kiddy-land/client/react";
import { Button } from "@workspace/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { useLocale } from "@workspace/ui/lib/i18n";

export function MembershipDashboard() {
  const { t } = useLocale(); const [selected, setSelected] = React.useState(""); const [search, setSearch] = React.useState(""); const members = useMembers(); const history = useMemberHistory(selected); const reissue = useReissueMemberCode(); const deactivate = useDeactivateMember(); const reactivate = useReactivateMember();
  const member = members.data?.find((value) => value.member.id === selected); const visibleMembers = members.data?.filter((value) => value.child.name.toLowerCase().includes(search.toLowerCase()) || value.member.code.toLowerCase().includes(search.toLowerCase()));
  return <Card><CardHeader><CardTitle>{t("membership.title")}</CardTitle></CardHeader><CardContent className="grid gap-3"><input className="h-9 border px-2" placeholder={t("membership.lookup")} value={search} onChange={(event) => setSearch(event.target.value)} /><div className="grid gap-2">{visibleMembers?.map((value) => <Button key={value.member.id} variant={selected === value.member.id ? "default" : "outline"} onClick={() => setSelected(value.member.id)}>{value.child.name} · {value.member.status} · {value.member.code}</Button>)}</div>{member ? <div className="grid gap-2 border p-3"><p><strong>{member.child.name}</strong> · {member.member.status} · {member.member.code}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => reissue.mutate({ id: member.member.id, reason: "Lost card" })}>{t("membership.reissue")}</Button>{member.member.status === "active" ? <Button size="sm" variant="outline" onClick={() => deactivate.mutate({ id: member.member.id, reason: "Owner deactivation" })}>{t("membership.deactivate")}</Button> : <Button size="sm" variant="outline" onClick={() => reactivate.mutate({ id: member.member.id, reason: "Owner reactivation" })}>{t("membership.reactivate")}</Button>}</div></div> : null}{selected ? <div className="grid gap-1 text-sm text-muted-foreground"><p>{t("membership.history")}: {history.data?.length ?? 0}</p>{history.data?.map((event) => <p key={event.id}>{event.type}{event.amount ? ` · IDR ${event.amount}` : ""}</p>)}</div> : null}</CardContent></Card>;
}
