import { useProducts, useCreateProduct, useUpdateProduct, useArchiveProduct, useReactivateProduct } from "@kiddy-land/client/react";
import { Button } from "@workspace/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { useLocale } from "@workspace/ui/lib/i18n";
import * as React from "react";

export function ProductCatalog() {
  const { t } = useLocale(); const products = useProducts(undefined); const create = useCreateProduct(); const update = useUpdateProduct(); const archive = useArchiveProduct(); const reactivate = useReactivateProduct(); const [sku, setSku] = React.useState(""); const [name, setName] = React.useState(""); const [barcode, setBarcode] = React.useState(""); const [price, setPrice] = React.useState(0); const [stock, setStock] = React.useState(0); const [threshold, setThreshold] = React.useState(0);
  return <Card><CardHeader><CardTitle>{t("inventory.catalog")}</CardTitle></CardHeader><CardContent className="grid gap-3"><div className="flex flex-wrap gap-2"><input className="h-10 border px-3" placeholder="SKU" value={sku} onChange={(e) => setSku(e.target.value)} /><input className="h-10 border px-3" placeholder={t("inventory.productName")} value={name} onChange={(e) => setName(e.target.value)} /><input className="h-10 border px-3" placeholder="Barcode" value={barcode} onChange={(e) => setBarcode(e.target.value)} /><input className="h-10 w-28 border px-3" type="number" min="0" placeholder={t("inventory.price")} value={price} onChange={(e) => setPrice(Number(e.target.value))} /><input className="h-10 w-24 border px-3" type="number" min="0" placeholder={t("inventory.lowStock")} value={threshold} onChange={(e) => setThreshold(Number(e.target.value))} /><input className="h-10 w-24 border px-3" type="number" min="0" value={stock} onChange={(e) => setStock(Number(e.target.value))} /><Button onClick={() => create.mutate({ sku, name, barcode, price, stock, lowStockThreshold: threshold })}>{t("inventory.create")}</Button></div>{products.data?.map((product) => <div className="flex justify-between border p-3" key={product.id}><span>{product.name} · {product.sku}</span><span className="flex items-center gap-2">{product.stock} · {product.archived ? "Archived" : "Active"}<Button size="sm" variant="outline" onClick={() => product.archived ? reactivate.mutate({ id: product.id }) : archive.mutate({ id: product.id })}>{product.archived ? "Reactivate" : "Archive"}</Button><Button size="sm" variant="outline" onClick={() => update.mutate({ id: product.id, price: product.price })}>Edit</Button></span></div>)}</CardContent></Card>;
}
