import * as React from "react";
import { usePublicProducts, usePublicTicket, useClientConnection, useSession, type PublicProduct, type PublicTicketResult } from "@kiddy-land/client/react";
import { formatIdr } from "@kiddy-land/localization";
import { useLocale } from "@workspace/ui/lib/i18n";
import { Button } from "@workspace/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/ui/components/card";

export function PublicKiosk() {
  const { locale, t } = useLocale(); const { state } = useClientConnection(); const { session } = useSession(); const [code, setCode] = React.useState(""); const [search, setSearch] = React.useState(""); const [ticketResult, setTicketResult] = React.useState<PublicTicketResult>(); const [publicProducts, setPublicProducts] = React.useState<PublicProduct[]>([]); const ticket = usePublicTicket(code.trim()); const products = usePublicProducts(search); const clearSafeState = React.useCallback(() => { setCode(""); setSearch(""); setTicketResult(undefined); setPublicProducts([]); }, []); React.useEffect(() => { if (!session || state === "read-only" || state === "disconnected") clearSafeState(); }, [clearSafeState, session, state]); React.useEffect(() => { if (ticket.data) setTicketResult(ticket.data); if (ticket.isError) clearSafeState(); }, [clearSafeState, ticket.data, ticket.isError]); React.useEffect(() => { if (products.data) setPublicProducts(products.data); if (products.isError) clearSafeState(); }, [clearSafeState, products.data, products.isError]);
  return <main className="grid min-h-dvh gap-6 bg-background p-6 md:grid-cols-2"><Card><CardHeader><CardTitle>{t("kiosk.ticketTitle")}</CardTitle></CardHeader><CardContent className="grid gap-3"><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); void ticket.refetch(); }}><label className="grid flex-1 gap-1 text-sm"><span className="text-xs font-medium text-muted-foreground">{t("kiosk.ticketCode")} *</span><input className="h-10 min-w-0 w-full border border-input bg-background px-3 font-mono text-sm" aria-label={t("kiosk.ticketCode")} value={code} onChange={(event) => setCode(event.target.value)} /></label><Button type="submit" disabled={!code.trim() || ticket.isFetching} className="self-end">{t("kiosk.check")}</Button></form>{ticketResult && <p className={ticketResult.ok ? "text-primary" : "text-destructive"}>{ticketResult.message} · {ticketResult.remainingMinutes} {t("kiosk.minutesRemaining")}</p>}{ticket.error && <p className="text-destructive">{t("kiosk.reconnect")}</p>}</CardContent></Card><Card><CardHeader><CardTitle>{t("kiosk.productTitle")}</CardTitle></CardHeader><CardContent className="grid gap-3"><label className="grid gap-1 text-sm"><span className="text-xs font-medium text-muted-foreground">{t("kiosk.search")}</span><input className="h-10 w-full border border-input bg-background px-3 text-sm" aria-label={t("kiosk.search")} placeholder={t("kiosk.search")} value={search} onChange={(event) => setSearch(event.target.value)} /></label>{publicProducts?.map((product) => <div className="flex justify-between border-b py-2" key={product.id}><span>{product.name}</span><strong>{formatIdr(product.price, locale)}</strong></div>)}{products.isError && <p className="text-destructive">{t("kiosk.reconnect")}</p>}</CardContent></Card></main>;
}
