import * as React from "react";
import { useLiveReport, useReport, reportExportUrl } from "@kiddy-land/client/react";
import { useClient } from "@kiddy-land/client/react";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/ui/components/card";
import { Button } from "@workspace/ui/components/button";
import { useLocale } from "@workspace/ui/lib/i18n";

type Financial = { data: { totals: { ticketRevenue: number; productRevenue: number; overtimeRevenue: number; grossRevenue: number; depositsReceived: number; refunds: number; voids: number } } };
export function ReportsDashboard() { const { t } = useLocale(); const client = useClient(); const today = new Intl.DateTimeFormat("en-CA").format(new Date()); const [from, setFrom] = React.useState(today); const [to, setTo] = React.useState(today); const [kind, setKind] = React.useState<"financial" | "playground" | "inventory" | "membership">("financial"); const filters = { from, to }; const financial = useReport<Financial>("financial", filters); const report = useReport<unknown>(kind, filters); const live = useLiveReport<{ data: { occupancy: number; activeMembers: number; lowStock: number } }>(); const result = kind === "financial" ? financial.data : report.data;
  const download = (format: "csv" | "pdf") => { const anchor = document.createElement("a"); anchor.href = reportExportUrl(client.origin, kind, filters, format); anchor.target = "_blank"; anchor.click(); };
  return <Card><CardHeader><CardTitle>{t("reports.title")}</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="flex flex-wrap gap-2"><input className="h-9 border px-2" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><input className="h-9 border px-2" type="date" value={to} onChange={(e) => setTo(e.target.value)} /><select className="h-9 border px-2" value={kind} onChange={(e) => setKind(e.target.value as typeof kind)}><option value="financial">Financial</option><option value="playground">Playground</option><option value="inventory">Inventory</option><option value="membership">Membership</option></select><Button onClick={() => download("csv")}>CSV</Button><Button variant="outline" onClick={() => download("pdf")}>PDF</Button></div><div className="grid gap-2 sm:grid-cols-3"><Metric label="Occupancy" value={live.data?.data.occupancy ?? 0} /><Metric label="Active members" value={live.data?.data.activeMembers ?? 0} /><Metric label="Low stock" value={live.data?.data.lowStock ?? 0} /></div>{financial.data?.data.totals ? <div className="grid gap-1 text-sm"><p>Ticket revenue: {financial.data.data.totals.ticketRevenue}</p><p>Product revenue: {financial.data.data.totals.productRevenue}</p><p>Overtime revenue: {financial.data.data.totals.overtimeRevenue}</p><p>Gross revenue: {financial.data.data.totals.grossRevenue}</p><p>Deposits received: {financial.data.data.totals.depositsReceived}</p><p>Refunds: {financial.data.data.totals.refunds}</p><p>Voids: {financial.data.data.totals.voids}</p></div> : <pre className="max-h-96 overflow-auto text-xs">{JSON.stringify(result, null, 2)}</pre>}</CardContent></Card>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div>; }
