import { useCallback, useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import "./App.css";

type Locale = "id" | "en";
type HostState = "starting" | "ready" | "unhealthy" | "fatal";
type HostStatus = { state: HostState; origin?: string; database?: string };
const origin = import.meta.env.VITE_LOCAL_SERVER_ORIGIN ?? "http://127.0.0.1:43117";
const copy = { id: { eyebrow: "KIDDY LAND / HOST", title: "Pusat operasi lokal", subtitle: "Satu host venue. Satu Local Server sebagai sumber kebenaran. Tanpa Internet.", readiness: "Kesiapan host", ready: "Local Server siap untuk operasi lokal", readyDescription: "Host dapat menerima koneksi klien lokal.", notReady: "Perubahan dinonaktifkan sampai kesiapan dikonfirmasi.", starting: "Local Server sedang dimulai", unhealthy: "Local Server tidak tersedia", fatal: "Local Server gagal dimulai", check: "Periksa lagi", stop: "Hentikan Local Server", local: "Lokal terlebih dahulu", localText: "Data operasional tetap berada di host venue.", authoritative: "Sumber kebenaran", authoritativeText: "Setiap klien membaca status server sebelum menulis.", database: "Database", unknown: "tidak diketahui" }, en: { eyebrow: "KIDDY LAND / HOST", title: "Local operation center", subtitle: "One venue host. One authoritative Local Server. No Internet required.", readiness: "Host readiness", ready: "Local Server ready for local operation", readyDescription: "The host can accept local client connections.", notReady: "Mutations remain unavailable until readiness is confirmed.", starting: "Local Server is starting", unhealthy: "Local Server is unavailable", fatal: "Local Server failed to start", check: "Check again", stop: "Stop Local Server", local: "Local first", localText: "Operational data stays on the venue host.", authoritative: "Authoritative", authoritativeText: "Every client reads server readiness first.", database: "Database", unknown: "unknown" } } as const;

async function readStatus(): Promise<HostStatus> { try { const response = await fetch(`${origin}/ready`); const report = await response.json() as { status?: HostState; database?: string }; return { state: report.status ?? (response.ok ? "ready" : "unhealthy"), origin, database: report.database }; } catch { return { state: "unhealthy", origin }; } }
export default function App() { const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem("kiddy-land-locale") as Locale) || "id"); const [status, setStatus] = useState<HostStatus>({ state: "starting" }); const [busy, setBusy] = useState(false); const t = copy[locale]; const check = useCallback(async () => { setBusy(true); setStatus(await readStatus()); setBusy(false); }, []); useEffect(() => { void check(); const timer = window.setInterval(() => void check(), 5000); return () => window.clearInterval(timer); }, [check]); function changeLocale(next: Locale) { setLocale(next); localStorage.setItem("kiddy-land-locale", next); } async function stop() { setBusy(true); await invoke("stop_host"); await check(); } const title = status.state === "ready" ? t.ready : status.state === "fatal" ? t.fatal : status.state === "starting" ? t.starting : t.unhealthy; return <main className="host-shell"><header><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="subhead">{t.subtitle}</p></header><div className="toolbar"><button onClick={() => changeLocale(locale === "id" ? "en" : "id")}>{locale === "id" ? "EN" : "ID"}</button><button onClick={() => void check()} disabled={busy}>{busy ? "…" : t.check}</button></div><section className="status-card"><div className="status-copy"><span className={`status-dot ${status.state}`} /><div><h2>{title}</h2><p>{status.state === "ready" ? t.readyDescription : t.notReady}</p></div></div><strong className={`pill ${status.state}`}>{status.state}</strong></section><section className="facts"><div><b>{t.local}</b><span>{t.localText}</span></div><div><b>{t.authoritative}</b><span>{t.authoritativeText}</span></div><div><b>{t.database}</b><span>{status.database ?? t.unknown}</span></div></section><div className="actions"><button className="quiet" onClick={() => void stop()} disabled={busy}>{t.stop}</button></div><footer>{origin}</footer></main>; }
