import type { CalendarStore } from "./calendar.ts";
import type { SaleStore } from "./sale.ts";
import type { LifecycleStore } from "./lifecycle.ts";
import type { InventoryStore } from "./inventory.ts";
import type { MembershipStore } from "./membership.ts";

export type ReportFilters = { from: string; to: string; cashierId?: string; paymentMethod?: string; packageId?: string; productId?: string; memberId?: string };
export type ReportEnvelope<T> = { kind: string; filters: ReportFilters; timezone: string; generatedAt: string; data: T };
function inRange(date: string, filters: ReportFilters) { return date >= filters.from && date <= filters.to; }
function validDate(value: string) { return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T12:00:00Z`)); }
function filterDefaults(calendar: CalendarStore, input: Partial<ReportFilters>): ReportFilters { const today = calendar.operatingDate(new Date()); const from = input.from ?? today; const to = input.to ?? from; if (!validDate(from) || !validDate(to) || from > to) throw new Error("Invalid report date range"); return { from, to, cashierId: input.cashierId, paymentMethod: input.paymentMethod, packageId: input.packageId, productId: input.productId, memberId: input.memberId }; }
export function createReportService(calendar: CalendarStore, sales: SaleStore, lifecycle: LifecycleStore, inventory: InventoryStore, membership: MembershipStore) {
  function filters(input: Partial<ReportFilters>) { return filterDefaults(calendar, input); }
  function financial(input: Partial<ReportFilters>): ReportEnvelope<unknown> { const f = filters(input); const rows = [...sales.sales.values()].filter((sale) => inRange(sale.operatingDate, f) && (!f.cashierId || sale.cashierId === f.cashierId) && (!f.paymentMethod || sale.paymentMethod === f.paymentMethod)).map((sale) => { const tickets = sale.lines.filter((line): line is Extract<typeof line, { kind: "ticket" }> => line.kind === "ticket" && (!f.packageId || sale.tickets.find((ticket) => ticket.id === line.ticketId)?.package.id === f.packageId) && (!f.memberId || line.memberId === f.memberId)); const products = sale.lines.filter((line): line is Extract<typeof line, { kind: "product" }> => line.kind === "product" && (!f.productId || line.productId === f.productId) && (!f.memberId || line.memberId === f.memberId)); return { saleId: sale.id, operatingDate: sale.operatingDate, cashierId: sale.cashierId, paymentMethod: sale.paymentMethod, ticketRevenue: tickets.reduce((n, line) => n + line.price, 0), productRevenue: products.reduce((n, line) => n + line.total, 0), total: tickets.reduce((n, line) => n + line.price, 0) + products.reduce((n, line) => n + line.total, 0), depositReceived: sale.deposits.reduce((n, deposit) => n + deposit.amount, 0), status: sale.status }; }); const ticketRevenue = rows.reduce((n, row) => n + row.ticketRevenue, 0); const productRevenue = rows.reduce((n, row) => n + row.productRevenue, 0); const overtime = lifecycle.events.filter((event) => event.type === "charge-collected" && inRange(calendar.operatingDate(new Date(event.at)), f)).reduce((n, event) => n + Number((event.details as { amount?: number })?.amount ?? 0), 0); return { kind: "financial", filters: f, timezone: calendar.timezone, generatedAt: new Date().toISOString(), data: { rows, totals: { ticketRevenue, productRevenue, overtimeRevenue: overtime, grossRevenue: ticketRevenue + productRevenue + overtime, depositsReceived: rows.reduce((n, row) => n + row.depositReceived, 0), refunds: inventory.refunds.filter((refund) => inRange(calendar.operatingDate(new Date(refund.at)), f)).reduce((n, refund) => n + refund.quantity, 0), voids: rows.filter((row) => row.status === "void").length } } }; }
  function playground(input: Partial<ReportFilters>): ReportEnvelope<unknown> { const f = filters(input); const events = lifecycle.events.filter((event) => inRange(calendar.operatingDate(new Date(event.at)), f)); const sessions = [...lifecycle.sessions.values()]; return { kind: "playground", filters: f, timezone: calendar.timezone, generatedAt: new Date().toISOString(), data: { occupancy: sessions.filter((session) => session.status === "active").length, entries: events.filter((e) => e.type === "admitted").length, exits: events.filter((e) => e.type === "exited").length, autoClosed: events.filter((e) => e.type === "auto-closed").length, overtimeMinutes: sessions.reduce((n, s) => n + s.overtimeMinutes, 0), events } }; }
  function inventoryReport(input: Partial<ReportFilters>): ReportEnvelope<unknown> { const f = filters(input); const movements = inventory.movements.filter((movement) => inRange(calendar.operatingDate(new Date(movement.at)), f) && (!f.productId || movement.productId === f.productId)); return { kind: "inventory", filters: f, timezone: calendar.timezone, generatedAt: new Date().toISOString(), data: { products: [...inventory.products.values()], movements, approvedCounts: inventory.counts.filter((count) => count.status === "approved"), pendingCounts: inventory.counts.filter((count) => count.status === "pending"), lowStock: inventory.list(undefined, false).filter((product) => product.stock <= product.lowStockThreshold) } }; }
  function membershipReport(input: Partial<ReportFilters>): ReportEnvelope<unknown> { const f = filters(input); const members = membership.list().filter((item) => !f.memberId || item.member.id === f.memberId); const events = membership.state.events.filter((event) => inRange(calendar.operatingDate(new Date(event.at)), f) && (!f.memberId || event.memberId === f.memberId)); const visits = [...sales.sales.values()].flatMap((sale) => sale.lines.filter((line): line is Extract<typeof line, { kind: "ticket" }> => line.kind === "ticket" && Boolean(line.memberId) && (!f.memberId || line.memberId === f.memberId)).map((line) => ({ saleId: sale.id, ticketId: line.ticketId, memberId: line.memberId, operatingDate: sale.operatingDate }))).filter((visit) => inRange(visit.operatingDate, f)); return { kind: "membership", filters: f, timezone: calendar.timezone, generatedAt: new Date().toISOString(), data: { members, events, visits } }; }
  function live() { return { kind: "live", timezone: calendar.timezone, generatedAt: new Date().toISOString(), data: { occupancy: [...lifecycle.sessions.values()].filter((s) => s.status === "active").length, activeMembers: membership.state.members.filter((m) => m.status === "active").length, lowStock: inventory.list(undefined, false).filter((p) => p.stock <= p.lowStockThreshold).length, products: inventory.products.size, sales: sales.sales.size } }; }
  return { filters, financial, playground, inventory: inventoryReport, membership: membershipReport, live };
}
export type ReportService = ReturnType<typeof createReportService>;
