import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useClient } from "../client-context";
import { canMutate, useConnectionStore } from "../connection/store";
import { clientQueryKeys } from "../query/query-client";
import type { ProductRecord, StockCount, StockMovement } from "../api/types";

export function useProducts(search?: string) { const client = useClient(); return useQuery({ queryKey: [...clientQueryKeys.products, search], queryFn: () => client.get<ProductRecord[]>(`/products${search ? `?search=${encodeURIComponent(search)}` : ""}`), staleTime: 5_000 }); }
export function useArchiveProduct() { const client = useClient(); const connection = useConnectionStore(); return useMutation({ mutationFn: ({ id }: { id: string }) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); return client.post<ProductRecord>(`/products/${id}/archive`, {}); } }); }
export function useReactivateProduct() { const client = useClient(); const connection = useConnectionStore(); return useMutation({ mutationFn: ({ id }: { id: string }) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); return client.post<ProductRecord>(`/products/${id}/reactivate`, {}); } }); }
export function useUpdateProduct() { const client = useClient(); const connection = useConnectionStore(); const queryClient = useQueryClient(); return useMutation({ mutationFn: ({ id, ...body }: { id: string; sku?: string; name?: string; barcode?: string; price?: number; lowStockThreshold?: number }) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); return client.patch<ProductRecord>(`/products/${id}`, body); }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: clientQueryKeys.products }); } }); }
export function useCreateProduct() { return mutation<ProductRecord>("/products"); }
export function useInventoryIntake() { return mutation<ProductRecord>("/inventory/intake"); }
export function useSubmitStockCount() { return mutation<StockCount>("/inventory/counts"); }
export function useApproveStockCount() { const client = useClient(); const connection = useConnectionStore(); return useMutation({ mutationFn: ({ id }: { id: string }) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); return client.post<StockCount>(`/inventory/counts/${id}/approve`, {}); } }); }
export function useInventoryMovements() { const client = useClient(); return useQuery({ queryKey: clientQueryKeys.inventoryMovements, queryFn: () => client.get<StockMovement[]>("/inventory/movements") }); }
export function useLowStock() { const client = useClient(); return useQuery({ queryKey: clientQueryKeys.lowStock, queryFn: () => client.get<ProductRecord[]>("/inventory/low-stock") }); }
export function useInventoryCounts() { const client = useClient(); return useQuery({ queryKey: clientQueryKeys.inventoryCounts, queryFn: () => client.get<StockCount[]>("/inventory/counts") }); }
export function useInventoryExceptions() { const client = useClient(); return useQuery({ queryKey: clientQueryKeys.inventoryExceptions, queryFn: () => client.get<Array<{ id: string; productId: string; quantity: number; reason: string; actorId: string; at: number }>>("/inventory/exceptions") }); }
export function useProductRefund() { const client = useClient(); const connection = useConnectionStore(); const queryClient = useQueryClient(); return useMutation({ mutationFn: ({ saleId, ...body }: { saleId: string; idempotencyKey: string; lineId: string; quantity: number; disposition: "return-to-stock" | "damaged-consumed"; reason: string }) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); return client.post(`/sales/${saleId}/refunds`, body); }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: clientQueryKeys.products }); void queryClient.invalidateQueries({ queryKey: clientQueryKeys.inventoryMovements }); void queryClient.invalidateQueries({ queryKey: clientQueryKeys.lowStock }); } }); }
function mutation<T>(path: string) { const client = useClient(); const queryClient = useQueryClient(); const connection = useConnectionStore(); return useMutation({ mutationFn: (body: unknown) => { if (!canMutate(connection.state, connection.synchronized)) throw new Error("Connection is not synchronized"); const resolved = typeof body === "object" && body !== null && "id" in body ? path.replace(":id", String((body as { id: string }).id)) : path; const payload = typeof body === "object" && body !== null && "id" in body ? Object.fromEntries(Object.entries(body).filter(([key]) => key !== "id")) : body; return client.post<T>(resolved, payload); }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: clientQueryKeys.products }); void queryClient.invalidateQueries({ queryKey: clientQueryKeys.inventoryMovements }); void queryClient.invalidateQueries({ queryKey: clientQueryKeys.lowStock }); } }); }
